### PR TITLE
Release nodejs-dlp v0.8.0

### PR DESCRIPTION
**Pull request by jkwlui**
This pull request was generated using releasetool.

### CODE REVIEW

**Comment by alexander-fenster** [comment]
Are we moving DLP to GA? If so, we must edit `.cloud-repo-tools.json` and regenerate `README.md` to mention it's GA. 

If we just need to release a new version because we dropped node4 and node9, we don't need to make it 1.0.0 since semver works differently in 0.x range. Just bumping minor is enough for 0.x.

**Review by alexander-fenster — CHANGES_REQUESTED** [review]
Putting Request changes just in case

**Comment by kinwa91** [comment]
Oh i see, I thought breaking change = major semver. 🤔

**Comment by alexander-fenster** [comment]
That's true in general but the reason for that is that the caret dependency (`"^1.2.3"`) will pick minor semver update but not major, so for breaking changes we do major. In 0.x range though, it works differently (`"^0.1.2"` will pick `0.1.3` but not `0.2.0`) so minor is enough. We only move to 1.0.0 when we GA the client library.

**Review by alexander-fenster — APPROVED** [review]

**Pull request merged**
