### PR TITLE
Add code samples for DLP text redaction

### PR DESCRIPTION
**Pull request by jmorrise**
The DLP team is in the process of expanding code samples to include features that we have launched since the initial samples were written. This pull request updates redact.js to include examples for redacting a string of text.

### CODE REVIEW

**Comment by jmorrise** [comment]
@stephenplusplus Who should I ask to review this? Thanks.

**Comment by stephenplusplus** [comment]
@crwilcox wdyt?

**Comment by jmorrise** [comment]
Thanks. This section of our documentation talks about configuratins: https://cloud.google.com/dlp/docs/redacting-sensitive-data

**Comment by kinwa91** [comment]
#93 should help fix `lint` check

**Comment by jmorrise** [comment]
@crwilcox All the checks pass for this pull request, can you merge it?

**Pull request merged**
