### PR TITLE
fix: replace GCLOUD_PROJECT with GOOGLE_CLOUD_PROJECT

### LINKED ISSUE #472: Samples Use Deprecated GCLOUD_PROJECT Variable
#### Steps to reproduce

1. gcloud config set project [PROJECT_ID]
2. node inspect.js string "test" 

Running any of the scripts in the sample directory will fail unless env variable GCLOUD_PROJECT is set to a valid project.  Gcloud [documentation](https://cloud.google.com/functions/docs/env-var?hl=en) says this variable is deprecated.  

`gcloud config set project` does however set GOOGLE_CLOUD_PROJECT to a valid project that can be used instead and will eliminate the manual setting of the env variable.

### PR DESCRIPTION
**Pull request by rogerthatdev**
Replace GCLOUD_PROJECT with GOOGLE_CLOUD_PROJECT which is automatically set with `gcloud config set project`

Fixes #472🦕

### CODE REVIEW

**Comment by sofisl** [comment]
@rogerthatdev, I think we just need to make sure we change the environment variable here so that Kokoro tests pass: https://github.com/googleapis/nodejs-dlp/blob/a5ec2f3baafbc770336596bdfe4737b61aba947e/.kokoro/samples-test.sh#L23

@bcoe or @JustinBeckwith , is there any reason why there are these two environment variables? Will changing this env variable break anything else?

**Comment by JustinBeckwith** [comment]
👋 I actually don't think this is the right approach.  Our docs and samples shouldn't require an env var for users trying to run the snippets.  We should always pass the `projectId` in as a parameter to the function.  It's ok for the tests to auto-detect the `projectId`, but even then - we should use `client.getProjectId()` to detect that rather than the env var.  

I think the "right" fix here is to make the projectId a required parameter for each sample, completely eliminate the usage of `GCLOUD_PROJECT` *and* `GOOGLE_CLOUD_PROJECT`, and use `client.getProjectId()` for the tests to pass into the samples.

**Comment by bcoe** [comment]
@JustinBeckwith @rogerthatdev I'm mainly concerned that we use the convention of `GCLOUD_PROJECT` in samples all over the place, seems like we should avoid changing it in one place. If it is a change we decided to take on, I'd want to make sure we have a plan to do it everywhere.

**Comment by sofisl** [comment]
I agree with @bcoe on this one - I've seen this in a lot of samples. What if, for now, we just make it optional to use either GCLOUD_PROJECT or GOOGLE_CLOUD_PROJECT as an environment variable to get the sample working with the SDK, until we have a more holistic strategy for this issue?

**Pull request closed without merging**
